

spring:
  datasource:
    driver-class-name: @database.driver@
    url: @database.url@
    username: @database.user@
    password: @database.password@

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    demo.project.vimpelcom.repositories: DEBUG
    org.jooq.tools.LoggerListener: INFO
