
spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: @database.driver@
    url: @database.url@
    username: @database.user@
    password: @database.password@

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.jooq.tools.LoggerListener: INFO
